testingground

diff --git a/docker/run-test b/docker/run-test
--- a/docker/run-test
+++ b/docker/run-test
@@ -12,7 +12,13 @@ if [[ ${CI_FS_MTR} == 'yes' ]]; then
 fi
 
 if [[ ${ZEN_FS_MTR} == "yes" ]] && [[ ${DOCKER_OS} == "ubuntu:hirsute" ]]; then
-    ZEN_FS_DOCKER_FLAG="--mount type=bind,source=/mnt/zenfs_disk_dir_${CMAKE_BUILD_TYPE},destination=/tmp/zenfs_disk_dir"
+    if [[ -f $SCRIPTS_DIR/zenfs ]]; then
+        sudo install --owner=root --group=root --mode=+rx $SCRIPTS_DIR/zenfs /usr/bin/
+        ZEN_FS_DOCKER_FLAG="--mount type=bind,source=/mnt/zenfs_disk_dir_${CMAKE_BUILD_TYPE},destination=/tmp/zenfs_disk_dir"
+    else
+        echo "Could not find zenfs utility."
+        exit 1
+    fi
 fi
 
 if [[ "${KEYRING_VAULT_MTR}" == 'yes' ]] && [[ ${DOCKER_OS} != 'centos:6' ]] && [[ ${DOCKER_OS} != 'i386/centos:6' ]]; then
@@ -48,7 +54,7 @@ docker run --rm \
     ${CI_FS_DOCKER_FLAG} \
     ${VAULT_DOCKER_FLAG} \
     ${ZEN_FS_DOCKER_FLAG} \
-    public.ecr.aws/e7j3v3n0/ps-build:${SOURCE_IMAGE//[:\/]/-} \
+    illiapshonkin/ps-7749:${SOURCE_IMAGE//[:\/]/-} \
     sh -c "
     set -o errexit
     set -o xtrace
